SET IDENTITY_INSERT [dbo].[AnimalType] ON 

INSERT [dbo].[AnimalType] ([AnimalTypeID], [Name]) VALUES (1, N'Mammal')
INSERT [dbo].[AnimalType] ([AnimalTypeID], [Name]) VALUES (2, N'Reptile')
INSERT [dbo].[AnimalType] ([AnimalTypeID], [Name]) VALUES (3, N'Amphibian')
INSERT [dbo].[AnimalType] ([AnimalTypeID], [Name]) VALUES (4, N'Bird')
INSERT [dbo].[AnimalType] ([AnimalTypeID], [Name]) VALUES (5, N'Fish')
SET IDENTITY_INSERT [dbo].[AnimalType] OFF
GO
SET IDENTITY_INSERT [dbo].[DietType] ON 

INSERT [dbo].[DietType] ([DietTypeID], [Name]) VALUES (1, N'Carnivore')
INSERT [dbo].[DietType] ([DietTypeID], [Name]) VALUES (2, N'Herbivore')
INSERT [dbo].[DietType] ([DietTypeID], [Name]) VALUES (3, N'Omnivore')
SET IDENTITY_INSERT [dbo].[DietType] OFF
GO
SET IDENTITY_INSERT [dbo].[State] ON 

INSERT [dbo].[State] ([StateID], [Name]) VALUES (1, N'Alabama')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (2, N'Alaska')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (3, N'Arizona')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (4, N'Arkansas')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (5, N'California')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (6, N'Colorado')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (7, N'Connecticut')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (8, N'Delaware')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (9, N'Florida')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (10, N'Georgia')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (11, N'Hawaii')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (12, N'Idaho')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (13, N'Illinois')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (14, N'Indiana')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (15, N'Iowa')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (16, N'Kansas')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (17, N'Kentucky')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (18, N'Louisiana')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (19, N'Maine')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (20, N'Maryland')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (21, N'Massachusetts')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (22, N'Michigan')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (23, N'Minnesota')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (24, N'Mississippi')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (25, N'Missouri')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (26, N'Montana')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (27, N'Nebraska')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (28, N'Nevada')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (29, N'New Hampshire')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (30, N'New Jersey')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (31, N'New Mexico')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (32, N'New York')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (33, N'North Carolina')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (34, N'North Dakota')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (35, N'Ohio')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (36, N'Oklahoma')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (37, N'Oregon')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (38, N'Pennsylvania')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (39, N'Rhode Island')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (40, N'South Carolina')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (41, N'South Dakota')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (42, N'Tennessee')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (43, N'Texas')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (44, N'Utah')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (45, N'Vermont')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (46, N'Virginia')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (47, N'Washington')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (48, N'West Virginia')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (49, N'Wisconsin')
INSERT [dbo].[State] ([StateID], [Name]) VALUES (50, N'Wyoming')
SET IDENTITY_INSERT [dbo].[State] OFF
GO